spring:
  application:
    name: energy-optimization-backend
  app:
    base-url: ${APP_BASE_URL:http://localhost:8080}
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
fastapi:
  server:
    url: ${FASTAPI_SERVER_URL}
allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:5500}